adj1 = input("Enter an adjective: (description) ")
noun = input("Enter a noun: (person, place, or thing) ")
adj2 = input("Enter another adjective: (description) ")
verb1 = input("Enter a verb ending in -ing: (action) ")
adj3 = input("Enter one more adjective: (description) ")

print()
print(f"Today I went to a {adj1} zoo.")
print(f"In an exhibit, I saw a {noun}.")
print(f"{noun} was {adj2} and {verb1}.")
print(f"I was {adj3}!")